### ISSUE TITLE
verbalize alerts count in the isotope vm

### ISSUE THREAD

**Issue by jparicka** [ProjectCloudly/cloudly#529]
e.g.: Koon (2)

**Comment by jparicka** [comment]
not applicable

**Comment by OndrejKopal** [comment]
Cus, muzes na jabber, ze by jsme pokecali o tom isotopu? A jak bylo v praci?




---------- Původní zpráva ----------

Od: Jan Paricka <notifications@github.com>

Komu: ProjectCloudly/cloudly <cloudly@noreply.github.com>

Datum: 28. 10. 2015 17:50:18

Předmět: Re: [cloudly] verbalize alerts count in the isotope vm (#529)


"

Closed #529(https://github.com/ProjectCloudly/cloudly/issues/529).

—

Reply to this email directly or view it on GitHub
(https://github.com/ProjectCloudly/cloudly/issues/529#event-448235272). 





"=
