### ISSUE TITLE
work in the ajax notif counter function

### ISSUE THREAD

**Issue by jparicka** [ProjectCloudly/Cloudly#534]

**Comment by jparicka** [comment]
see the line 103 to see how to go about this....
https://github.com/ProjectCloudly/cloudly/blob/master/dashboard/views.py

**Comment by OndrejKopal** [comment]
Cus, muzes na jabber?


---------- Původní zpráva ----------

Od: Jan Paricka <notifications@github.com>

Komu: ProjectCloudly/cloudly <cloudly@noreply.github.com>

Datum: 27. 10. 2015 19:24:17

Předmět: Re: [cloudly] work in the ajax notif counter function (#534)


"

see the line 103 to see how to go about this....

https://github.com/ProjectCloudly/cloudly/blob/master/dashboard/views.py
(https://github.com/ProjectCloudly/cloudly/blob/master/dashboard/views.py)

—

Reply to this email directly or view it on GitHub
(https://github.com/ProjectCloudly/cloudly/issues/534#issuecomment-151599629)
. 





"=

**Comment by jparicka** [comment]
tbd (to be decided)..
