### ISSUE TITLE
custom monitoring and/or plugins?

### ISSUE THREAD

**Issue by muhahacz** [ProjectCloudly/Cloudly#574]
Ahoj :), 
Is possible to add custom monitoring ?
For example using of own scripts, i am searching for alternative for munin. 
lm-sensors + custom commands would be great (..using hdparm to check if disk is in standby or active mode). 
Unfortunately i cant find any information about custom plugins / commands.
Diky

**Comment by jparicka** [comment]
Ahoy Lukas!

The short answer to your question is Yes - there is a way to add on custom metricts to monitor but unfortunately there's no easy way to do so at the moment as we are very much in the prototyping stage and this is something that is still in the todo. :/

Do you have any particular metrics in mind?  Perhaps I can try and add them in for you..?

Let me know.  Cheers :)

**Comment by jparicka** [comment]
PS - I really would do if you give us a star on github... ;-)

**Comment by jparicka** [comment]
Alternativelly see the agent.py whether you'd be able to incirporate that in yourself. It's the open source on the end of the day and we could use every hand! :)

**Comment by jparicka** [comment]
Well, it's definitely in the todo, though..!
And it's quite a good idea.. :+1:

**Comment by muhahacz** [comment]
Star is given :)

I wrote a basic script for munin to check if hdd is in standby or active mode. Check it out:
https://github.com/muhahacz/hdd_spindown_checker_munin_plugin/blob/master/spindown.pl

There is official plugin for lm-sensors:
http://munin-monitoring.org/browser/munin-contrib/plugins/sensors/hwmon

It is great to check CPU temp, Fan speed, etc...
I am searching for better alternative for munin and i found this /ihope/ great project ;)

**Comment by jparicka** [comment]
On it! :)

**Comment by jparicka** [comment]
We'll have that in in later release..
