### ISSUE TITLE
editing Account Settings does not work

### ISSUE THREAD

**Issue by shekhrd** [ProjectCloudly/Cloudly#624]
Issue:
Account Settings can't be changed.

Detailed:
Clicking on the spanner icon on the Account Settings screen does not unlock the settings for editing.

Expected:
Clicking the spanner icon enables settings for editing and shows Save Settings button

**Comment by jparicka** [comment]
this will be addressed once we switch over to reactjs...
at the mo we're trying to clear up the list...
hence closing the issue for the time being..
thanks for pointing that out though! :+1:
