### ISSUE TITLE
Unknown command 'syncdb'

### ISSUE THREAD

**Issue by KarimJedda** [ProjectCloudly/Cloudly#702]
I'm getting an error at the installation:
xxx:cloudly xxx$ python manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.

and python manage.py help gives:

xxx:cloudly xxx$ python manage.py help

Type 'manage.py help <subcommand>' for help on a specific subcommand.

Available subcommands:

[auth]
    changepassword
    createsuperuser

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

any idea what happened there?
Thanks a lot

**Comment by jparicka** [comment]
Hi there,
You'd need to upgrade Django to the latest version.

**Comment by KarimJedda** [comment]
Hi,
is this not the latest version? 
xxx:cloudly xxx$ python -c "import django; print(django.get_version())"
1.9.1

Thanks

**Comment by KarimJedda** [comment]
This guy says: http://stackoverflow.com/questions/28685931/unknown-command-syncdb-running-python-manage-py-syncdb
"If you look at the release notes for django 1.9, syncdb command is removed.

Please use migrate instead. Moving forward, the migration commands would be as documented here"

is it the case?

**Comment by jparicka** [comment]
Oh dear, that's definitely the case.  I didn't know they removed syncdb from the latest django?

**Comment by KarimJedda** [comment]
Neither do I, but I'm trying to see what I can do to help. 
When calling migrate, it doesn't create the tables and results in: ProgrammingError: (1146, "Table 'cloudly.userprofile_profile' doesn't exist") when logging in for example. 
Where should I have a look?
Cheers

**Comment by jparicka** [comment]
Karim, erm, you do realise that we're very much in the development / prototyping process at this stage..
Basically all you get if/when you successfully run Cloudly in "Enterprise mode", all you get is what you see on http://projectcloudly.org/demo/

**Comment by jparicka** [comment]
Give me 5 mins I'll look into what is the alternative for the syncdb...

**Comment by KarimJedda** [comment]
It's alright, I'm willing to contribute also, I just need some guidance to start. I will use this extensively so I thought I'd help too :)

**Comment by jparicka** [comment]
http://stackoverflow.com/questions/29683494/what-should-i-use-instead-of-syncdb-in-django-1-9

**Comment by jparicka** [comment]
Rock star!  I just sent you the invite! :+1:

**Comment by KarimJedda** [comment]
Great! 
This seems to do the job:
python manage.py migrate --run-syncdb

**Comment by jparicka** [comment]
Please try:

$ python manage.py makemigrations
$ python manage.py migrate

..and let me know if that worked.

Btw I'd be more than happy to assist you on the OpenTSDB as well!

**Comment by jparicka** [comment]
Wicked, I'll update the documentation.
Thanks, Karim! :)

**Comment by KarimJedda** [comment]
You're welcome man, props for this awesome tool. 
Alright, I'll get back to you as soon as I advance a bit more.
Thanks!!
